# Generated by Django 4.1.7 on 2023-03-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamCandidates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examDate", models.DateTimeField()),
                ("exam_taken", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("jobCode", models.CharField(max_length=255)),
                ("jobGrade", models.CharField(max_length=20)),
                ("totalquestions", models.IntegerField(default=3)),
                ("allowedtime", models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("cha", models.CharField(max_length=255)),
                ("chb", models.CharField(max_length=255)),
                ("chc", models.CharField(max_length=255)),
                ("chd", models.CharField(max_length=255)),
                ("ans", models.CharField(max_length=255)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        related_query_name="job",
                        to="questions.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examDate", models.DateTimeField(auto_now_add=True)),
                ("userAnswer", models.TextField()),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.job",
                    ),
                ),
            ],
        ),
    ]
