# Generated by Django 4.1.7 on 2023-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
    ]
