# Generated by Django 4.1.7 on 2023-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0002_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
